version: '3.8'

services:
  auth_server:
    build:
      context: ./auth_server
    container_name: auth_server
    ports:
      - "8000:8000"
    networks:
      - backend

  client_server:
    build:
      context: ./client_server
    container_name: client_server
    ports:
      - "8002:8002"
    networks:
      - backend

  resource_server:
    build:
      context: ./resource_server
    container_name: resource_server
    ports:
      - "8001:8001"
    networks:
      - backend

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - auth_server
      - client_server
      - resource_server
    networks:
      - backend

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    command: ["ngrok", "http", "proxy:80"]
    ports:
      - "4040:4040"
    depends_on:
      - proxy
    environment:
      - NGROK_AUTHTOKEN=2v3ZWz3NM29Og9xBtkwuxNq5DJ4_2ZJuHHeLcVhAmGEgHcLqq
    networks:
      - backend

networks:
  backend:
    driver: bridge
