version: '3.8'

services:
  auth_server:
    build:
      context: ./auth_server
    container_name: auth_server
    depends_on:
      ngrok:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend

  client_server:
    build:
      context: ./client_server
    container_name: client_server
    depends_on:
      ngrok:
        condition: service_healthy
    ports:
      - "8002:8002"
    networks:
      - backend

  resource_server:
    build:
      context: ./resource_server
    container_name: resource_server
    depends_on:
      ngrok:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - backend

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      auth_server:
        condition: service_started
      client_server:
        condition: service_started
      resource_server:
         condition: service_started
      ngrok:
        condition: service_healthy
    networks:
      - backend

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    command: ["ngrok", "http", "proxy:80"]
    ports:
      - "4040:4040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/api/tunnels"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - NGROK_AUTHTOKEN=2v3ZWz3NM29Og9xBtkwuxNq5DJ4_2ZJuHHeLcVhAmGEgHcLqq
    networks:
      - backend

networks:
  backend:
    driver: bridge
