# Generated by Django 5.2.1 on 2025-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthTokenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
