# Generated by Django 4.2.21 on 2025-06-01 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='patient_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='blurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='dummy_name_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='face_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='identifying_marks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('averaged_to', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
        ),
    ]
