# Generated by Django 4.2.21 on 2025-06-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_rename_uploaded_at_photo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='identifying_marks',
        ),
    ]
