# Generated by Django 4.2.21 on 2025-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_image_photoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
