# Generated by Django 5.1.7 on 2025-06-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_biometricdata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to='photos.photo'),
        ),
    ]
