# Generated by Django 4.2.23 on 2025-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_biometricdata_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
