# Generated by Django 4.2.23 on 2025-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photoimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='image',
            field=models.ImageField(upload_to='originals/'),
        ),
    ]
